name: Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [2.1.802]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      # Fix for https://github.com/actions/setup-dotnet/issues/29#issuecomment-548740241
      uses: actions/setup-dotnet@bb95ce727fd49ec1a65933419cc7c91747785302
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build and Test (.sh)
      if: matrix.os != 'windows-latest'
      run: ./build.sh
    - name: Build and Test (.cmd)
      if: matrix.os == 'windows-latest'
      run: .\build.cmd
